import assert from 'node:assert/strict';import {build} from 'esbuild';
const compiled=await build({stdin:{contents:`export * from './examples/project/reporting-data';export * from './examples/project/risk-data';`,resolveDir:process.cwd()},bundle:true,write:false,format:'esm',platform:'node'});
const {ledger,financialRows,productivityRows,traceRows,riskPayload,riskFetch,resetRisk,timingPayload}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
assert.equal(ledger.length,240);assert.equal(new Set(ledger.map(r=>r.id)).size,240);
const sum=(rows,key)=>rows.reduce((n,r)=>n+r[key],0);
for(const scale of ['week','month']){const rows=financialRows(scale);for(const [summary,source] of [['actual_hours','hours'],['actual_cost','cost'],['actual_revenue','revenue']]){assert.equal(sum(rows,summary),sum(ledger,source));for(const r of rows)assert.equal(sum(traceRows(r.period,scale),source),r[summary]);const selected=rows[2];assert.equal(sum(traceRows(selected.period,scale,undefined,true),source),sum(rows.slice(0,3),summary));}assert.equal(sum(productivityRows(scale),'total_hours'),sum(ledger,'hours'));for(const phase of productivityRows(scale)){assert.equal(sum(phase.weekly,'hours'),phase.total_hours);for(const week of phase.weekly){const raw=traceRows(week.week,scale,phase.phase);assert.equal(week.metric,sum(raw,'hours')/new Set(raw.map(r=>r.worker)).size)}}}
console.log('PASS reporting: 240 unique records; weekly/monthly/cumulative totals and drilldowns conserve hours, cost and revenue');
const risk=riskPayload();assert.equal(risk.signals.length,risk.kpis.total);assert.equal(sum(risk.by_source,'n'),risk.kpis.total);assert.equal(sum(risk.projects,'n'),risk.kpis.total);assert.equal(risk.trend.at(-1).total,risk.kpis.total);assert.equal(risk.kpis.p1+risk.kpis.p2+risk.kpis.p3,risk.kpis.total);
const timing=timingPayload();assert.ok(timing.incidents.filter(x=>x.first_action_at).every(x=>x.first_ack_at));
const correlation=risk.raid_correlations[0],link=correlation.links[0];await riskFetch('/api/risk/correlations',{method:'POST',body:JSON.stringify({raid_item_id:correlation.raid_id,signal_id:link.signal_id,action:'confirm'})});assert.equal(riskPayload().raid_correlations[0].links[0].match_kind,'manual');await riskFetch('/api/risk/correlations',{method:'POST',body:JSON.stringify({raid_item_id:correlation.raid_id,signal_id:link.signal_id,action:'dismiss'})});assert.ok(!riskPayload().raid_correlations[0].links.some(x=>x.signal_id===link.signal_id));assert.equal(riskPayload().signals.length,risk.kpis.total);resetRisk();assert.equal(riskPayload().raid_correlations[0].links.length,2);
console.log('PASS risk: portfolio aggregates, trend endpoint, response sequence, confirm/dismiss and reset');
