import Image from "next/image";
import Link from 'next/link';
const stories={
 project:{eyebrow:'Inside the application',title:'A dashboard is the start of the conversation.',intro:'The useful work happens when someone asks why a number changed, which activity is affected, or what the team should do next. This workspace makes those questions explorable.',sections:[
 ['Bring the schedule into the system','The MS Project pipeline extracts task hierarchy, dates, resource assignments, baselines, and predecessor links. The review step shows what arrived before it becomes a working schedule. Comparing revisions separates added, removed, and changed activities so a revised finish date is visible rather than buried in a replacement file.','Try parsing both bundled XML revisions. Three configuration activities move by twelve days.'],
 ['Keep planning and performance connected','The Gantt keeps the work breakdown aligned with its timeline. Capacity heatmaps reveal the roles and periods where demand exceeds allocation. Cost and productivity views share a source ledger, so period totals can be checked against the exact entries behind them.','Switch to cumulative cost, open a plotted amount, and inspect the records through that period.'],
 ['Make review decisions visible','Forecast revisions separate an editable estimate from an approved snapshot. The risk view brings schedule, cost, quality, staffing, and forecast signals into one portfolio review, with response timing and suggested relationships that a reviewer can confirm or dismiss.','Change remaining hours, approve a snapshot, then open a revision. The earlier approved values remain available.']
 ],scope:'Adapted application code includes the WBS/Gantt, heatmap grid, financial and productivity charts, quality chart, full risk page, matching logic, hierarchy mapper, version comparison, and Python parser. The portfolio uses fictional scenarios and local review state; it does not connect to client systems.',service:'project-controls',cta:'Build a clearer view of your delivery work.'},
 inspection:{eyebrow:'Inside the workbench',title:'From a risk curve to a reviewable task plan.',intro:'Inspection timing involves more than choosing a date. The workbench brings together asset condition, consequence, task effect, timing constraints, and review gates so the proposed plan can be questioned.',sections:[
 ['Start with the governing assessment','Contributor rankings help locate the assets and assessments driving the scenario. Lifetime curves expose how the current and proposed plans affect the selected risk measure. Changing the measure or scenario makes the tradeoff visible before changing a task.','Choose a process area, select an asset, and compare its current and proposed curves.'],
 ['Inspect the reason for the proposal','Task credits, defaults, timing windows, and acceptance checks constrain the calculation. The result distinguishes work to pull forward, keep, add, or send for engineering review. The task-pool view gives a second way to inspect which task bundles address which assessments.','Open Settings and the task-pool heatmap, change an assumption, and rerun the scenario.'],
 ['Carry context into the handoff','The cost-benefit workbook includes assessment and task-level detail. The import workbook includes the proposed tasks, links, steps, and a separate flags-and-holds sheet. A flagged proposal remains visibly flagged in the exported material.','Export both workbooks. Compare the task rows and review notes with the on-screen assessment.']
 ],scope:'This example uses the original workbench and calculation engine with 18 invented assets and 36 synthetic assessments. Curves, costs, limits, and timing are demonstration inputs. The outputs illustrate the workflow and are not a validated inspection recommendation for operating equipment.',service:'engineering',cta:'Turn a technical model into a usable workflow.'},
 integration:{eyebrow:'Inside the reconciliation',title:'An integration needs a review path.',intro:'Moving records between systems is only part of the problem. Different labels, missing mappings, duplicate submissions, and uncertain destinations need to be visible to the person responsible for the result.',sections:[
 ['Match what can be matched','The original deterministic matching logic compares source phase and task labels against a target work breakdown. The confidence threshold makes the matching decision explicit and leaves unresolved records available for review.','Filter to Unmapped. The source includes an unclassified support entry and a near-match task name.'],
 ['Give exceptions a destination','A hierarchy picker exposes the available work packages and their breadcrumbs. A manual selection records a deliberate mapping without changing the source entry. Applied hours can then be inspected by phase, task, and contributing source bucket.','Assign Unclassified support to a work package, apply the mapped rows, and inspect the destination tree.'],
 ['Check the handoff','The example keeps source, mapped, unmapped, and applied totals separate. Exporting the receipt gives the reviewer a record of the local application step. This is the pattern used to make an integration explainable when someone challenges a total.','Confirm that source hours equal mapped plus unmapped hours before and after the manual mapping.']
 ],scope:'The matcher, destination picker, and hours hierarchy are adapted from the original application. Source records and destinations are fictional. Application is a local demonstration snapshot, not a write to an external timesheet or project system.',service:'integrations',cta:'Connect your systems with a traceable handoff.'}
};
export function WorkExplained({kind}:{kind:keyof typeof stories}){const s=stories[kind];return <section className="site-container work-explained"><header><p className="eyebrow">{s.eyebrow}</p><h2>{s.title}</h2><p>{s.intro}</p>{kind==='project'&&<figure className="work-story-figure"><Link href="/demos/project-controls?view=8"><Image src="/images/work/risk-workspace.webp" width={1200} height={833} alt="Risk workspace showing a fictional portfolio trend and schedule-cost matrix" sizes="(max-width: 760px) 100vw, 35vw" /></Link><figcaption>Open the portfolio risk view ↗</figcaption></figure>}</header><div className="work-explanation-list">{s.sections.map(([title,body,tryIt],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{body}</p><p className="try-it"><strong>Try it:</strong> {tryIt}</p></div></article>)}</div><details><summary>What this example includes</summary><p>{s.scope}</p></details><div className="work-explained-cta"><p>{s.cta}</p><Link className="button-primary" href={`/contact?service=${s.service}`}>Discuss a project <span aria-hidden="true">↗</span></Link></div></section>}
export function WorkFeatureIndex(){return <section className="site-container work-feature-index"><div><p className="eyebrow">Go straight to the detail</p><h2>Choose the question you want to explore.</h2></div><div>{[['What changed in the schedule?','MS Project import & revision review',2],['Where are we short on capacity?','Role demand & allocation heatmaps',1],['Where did this cost come from?','Cost, margin & source records',6],['Is effort turning into output?','Productivity by phase',7],['Which projects need attention?','Risk signals & response timing',8],['What will the remaining work cost?','Forecast revisions & snapshots',4]].map(([q,label,view])=><Link key={String(view)} href={`/demos/project-controls?view=${view}`}><span><strong>{q}</strong><small>{label}</small></span><span aria-hidden="true">↗</span></Link>)}</div></section>}
