export const roles=['Project lead','Process engineer','Mechanical engineer','Controls engineer','Data analyst','Quality reviewer'];
export const rates=[125,110,105,115,85,95];
const DAY=864e5;
export const date=(offset:number)=>new Date(Date.UTC(2026,7,3)+offset*DAY).toISOString().slice(0,10);
const base={baseline_count:0,baseline_metric:null,baseline_uom:null,actual_count:0,actual_metric:null,actual_uom:null,completed_count:0,comments:'Fictional portfolio example',lag_days:0,milestone_count:0};
export let rows:any[]=[];
rows.push({...base,id:'program',parent_id:null,type:'project',level:0,depth:0,name:'Atlas delivery program',has_children:true,start_date:date(0),end_date:date(225),baseline_start:date(0),baseline_end:date(210),percent_complete:35,baseline_hours:0,actual_hours:0,remaining_hours:0,total_hours:0,baseline_cost:0,actual_cost:0,remaining_cost:0,schedule_cost:0,is_critical:true,wbs_code:'1'});
for(let p=0;p<4;p++){
 const phaseId=`phase-${p}`,phase=['Definition','Engineering','Delivery','Assurance'][p];
 rows.push({...rows[0],id:phaseId,parent_id:'program',type:'phase',level:1,depth:1,name:phase,wbs_code:`1.${p+1}`,start_date:date(p*42),end_date:date(p*42+80),baseline_start:date(p*42),baseline_end:date(p*42+70)});
 for(let t=0;t<8;t++){
  const n=p*8+t,resource=roles[n%roles.length],hours=80+(n%5)*24,actual=Math.round(hours*[1,.9,.65,.35,.15,0][Math.min(5,Math.floor(n/5))]),remaining=Math.max(0,hours-actual)+(n%4)*8;
  rows.push({...base,id:`task-${n}`,parent_id:phaseId,type:'task',level:2,depth:2,name:[['Scope definition','Site survey','Requirements register','Basis of design','Stakeholder review','Estimate preparation','Scope approval','Definition gate'],['Process calculations','Equipment specification','Layout development','Control philosophy','Design review','Drawing revisions','Design approval','Engineering gate'],['Procurement package','Supplier review','Fabrication review','Installation plan','Systems configuration','Site integration','Commissioning','Delivery gate'],['Inspection plan','Verification records','Functional testing','Defect resolution','Training','Operating procedures','Handover package','Acceptance milestone']][p][t],has_children:false,start_date:date(p*42+t*7),end_date:date(p*42+t*7+(t===7?0:21+n%8)),baseline_start:date(p*42+t*7),baseline_end:date(p*42+t*7+(t===7?0:21)),days_required:21,baseline_hours:hours,actual_hours:actual,remaining_hours:remaining,total_hours:actual+remaining,baseline_cost:hours*rates[n%6],actual_cost:actual*rates[n%6],remaining_cost:remaining*rates[n%6],schedule_cost:(actual+remaining)*rates[n%6],percent_complete:Math.round(actual/hours*100),is_critical:n%3===0,is_milestone:t===7,total_float:n%3===0?0:7,resource,predecessor_task_id:n?`task-${n-1}`:null,predecessor_name:n?'Previous work package':null,relationship:'FS',projected_finish:date(p*42+t*7+28),wbs_code:`1.${p+1}.${t+1}`});
 }
}
for(const parent of [...rows].reverse().filter(r=>r.has_children)) {const children=rows.filter(r=>r.parent_id===parent.id);for(const key of ['baseline_hours','actual_hours','remaining_hours','total_hours','baseline_cost','actual_cost','remaining_cost','schedule_cost'])parent[key]=children.reduce((sum,r)=>sum+r[key],0);parent.percent_complete=parent.baseline_hours?Math.round(parent.actual_hours/parent.baseline_hours*100):0;parent.milestone_count=children.reduce((sum,r)=>sum+(r.is_milestone?1:r.milestone_count||0),0);}
export const originalRows=structuredClone(rows);
export function replaceRows(next:any[]){rows=next;window.dispatchEvent(new Event('demo-data-change'))}
export async function demoFetch(url:string){const data=url.includes('/changes')?{changes:[{change_type:'adjust_task',target_id_before:'task-12',payload:{after:{start_date:date(78),end_date:date(125),remaining_hours:160}}}]}:url.includes('/scenarios')?{scenarios:[{id:'capacity-shift',name:'Additional design review',status:'draft'}]}:{success:true,rows};return new Response(JSON.stringify(data),{headers:{'content-type':'application/json'}})}
export function downloadCsv(name:string,data:any[]){const keys=Object.keys(data[0]||{});const quote=(v:any)=>'"'+String(v??'').replaceAll('"','""')+'"';const a=document.createElement('a');const url=URL.createObjectURL(new Blob([[keys.map(quote).join(','),...data.map(r=>keys.map(k=>quote(r[k])).join(','))].join('\n')],{type:'text/csv'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
