import {useState} from 'react';
import {originalRows,rates,roles,downloadCsv} from './data';
import VarianceBar from './components/forecast/VarianceBar';
import Sparkline from './components/forecast/Sparkline';
import ApprovalTrail from './components/forecast/ApprovalTrail';
const initial=originalRows.filter(r=>r.type==='task');
const usd=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export default function Forecast(){const [tasks,setTasks]=useState(initial),[status,setStatus]=useState('Draft'),[trail,setTrail]=useState<any[]>([]),[snapshots,setSnapshots]=useState<any[]>([]),[phase,setPhase]=useState('All phases');const total=(key:string)=>tasks.reduce((s,r)=>s+r[key],0);const baseline=total('baseline_cost'),actual=total('actual_cost'),remaining=tasks.reduce((s,r)=>s+r.remaining_hours*rates[roles.indexOf(r.resource)],0);const visible=tasks.filter(t=>phase==='All phases'||t.parent_id===phase);
 function action(next:string){setStatus(next);setTrail([...trail,{actor_name:next==='Submitted'?'Sample project lead':'Sample reviewer',actor_role:'Demo',action:next.toLowerCase(),at:new Date().toISOString(),comment:'Local demonstration action'}]);if(next==='Approved')setSnapshots([...snapshots,{version:snapshots.length+1,forecast:actual+remaining,rows:structuredClone(tasks)}])}
 return <div className="example-body"><h2>Forecast worksheet & review</h2><p>Role-based pricing, remaining-effort changes, cost variance, and a frozen approval record. The variance bars, sparklines, and approval trail are original platform components. The local workflow uses fictional roles and costs.</p><div className="example-stats"><span>Baseline<strong>{usd(baseline)}</strong></span><span>Actual cost<strong>{usd(actual)}</strong></span><span>Remaining cost<strong>{usd(remaining)}</strong></span><span>Forecast at completion<strong>{usd(actual+remaining)}</strong></span><span>Status<strong>{status}</strong></span></div><div className="example-controls"><label>Phase<select value={phase} onChange={e=>setPhase(e.target.value)}><option>All phases</option>{originalRows.filter(r=>r.type==='phase').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="btn" disabled={status!=='Draft'} onClick={()=>action('Submitted')}>Submit forecast</button><button className="btn" disabled={status!=='Submitted'} onClick={()=>action('Approved')}>Approve snapshot</button><button className="btn" disabled={status==='Draft'} onClick={()=>action('Draft')}>Open revision</button><button className="btn" onClick={()=>downloadCsv('sample-forecast.csv',tasks)}>Export worksheet ↓</button></div><div className="example-scroll"><table className="example-table"><thead><tr>{['Work package','Role / rate','Baseline','Actual','Remaining hours','Forecast','Variance'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(t=>{const rate=rates[roles.indexOf(t.resource)],eac=t.actual_cost+t.remaining_hours*rate;return <tr key={t.id}><td>{t.name}</td><td>{t.resource}<br/>{usd(rate)}/h</td><td>{usd(t.baseline_cost)}</td><td>{usd(t.actual_cost)}</td><td><input aria-label={`Remaining hours for ${t.name}`} type="number" min="0" max="10000" disabled={status!=='Draft'} value={t.remaining_hours} onChange={e=>setTasks(tasks.map(r=>r.id===t.id?{...r,remaining_hours:Math.max(0,Math.min(10000,Number(e.target.value)))}:r))}/></td><td>{usd(eac)}</td><td><VarianceBar value={eac} baseline={t.baseline_cost}/></td></tr>})}</tbody></table></div><div className="example-controls"><h3>Approved snapshots</h3><Sparkline data={snapshots.map(s=>s.forecast)} width={180} height={35}/></div>{snapshots.length?snapshots.map(s=><div className="example-note" key={s.version}>Revision {s.version} · {usd(s.forecast)} <button className="btn" onClick={()=>downloadCsv(`sample-forecast-v${s.version}.csv`,s.rows)}>Download frozen rows</button></div>):<p>Submit and approve a forecast to preserve its values here. Later edits will not change an approved snapshot.</p>}<ApprovalTrail trail={trail}/></div>
}
