export const views=['Schedule','Capacity heatmaps','MS Project import','Hours mapping','Forecast','Quality','Cost & margin','Productivity','Risk intelligence','Start here'];
export const guides=[
 {question:'What is driving the finish date?',purpose:'Connect the work breakdown, dates, dependencies, resources, and baseline in a single schedule.',steps:['Expand a phase, then search for a work package.','Switch from Months to Weeks and compare baseline versus projected finish.','Turn on Critical, inspect dependencies, and export the schedule.'],detail:'The split panes stay aligned while you scroll. Column selection and resizing let a project lead review dates while an analyst reviews hours, cost, float, and predecessors.'},
 {question:'Where does demand exceed capacity?',purpose:'Review the same planning horizon from the work-demand and available-capacity sides.',steps:['Choose one role and switch display units between FTE and hours.','Show capacity gap, then add 1 FTE to test a staffing decision.','Select a cell to inspect its value; both grids scroll together.'],detail:'The example uses a 160-hour month. Daily and weekly views inherit monthly source values, so the display does not imply a detailed daily allocation model.'},
 {question:'What changed in the latest schedule?',purpose:'Turn a Project file into reviewable rows before accepting a revision.',steps:['Parse sample v1 to inspect hierarchy, resources, costs, and dependencies.','Compare sample v2, then open Version changes to see three shifted tasks.','Open the imported Gantt and inspect the resulting schedule.'],detail:'The sample files pass through the actual Python/MPXJ parser and hierarchy mapper. An imported plan replaces the schedule view for this session; other demonstrations retain their own clearly labeled scenarios.'},
 {question:'Can every applied hour be traced?',purpose:'Reconcile source time-entry labels with the project’s work breakdown.',steps:['Show Unmapped to find the two exceptions.','Choose a destination for Unclassified support and apply the reviewed mapping.','Inspect the hours tree, then export a receipt.'],detail:'Matching runs locally using the original deterministic matcher. Source hours equal mapped plus unmapped hours; only mapped records enter the applied snapshot.'},
 {question:'What does the remaining work now cost?',purpose:'Expose the effect of an effort revision before it enters an approved forecast.',steps:['Change remaining hours on a work package.','Observe the forecast and variance, then Submit forecast.','Approve a snapshot, open a revision, and confirm the earlier snapshot stays frozen.'],detail:'Role rates translate remaining hours into cost. The approval trail demonstrates the review sequence; this portfolio example does not authenticate separate reviewers.'},
 {question:'Is quality improving, or is work accumulating?',purpose:'Read inspection effort, rework, and defect counts together.',steps:['Compare Hours, Ratios, and Defects.','Switch between period and cumulative views, and month/week grouping.','Toggle a series and open the source weeks below the chart.'],detail:'The measures are fictional weekly observations. Open defects are a point-in-time balance, while defects found are a period count; those measures should not be interpreted interchangeably.'},
 {question:'What is behind the commercial trend?',purpose:'Compare revenue, labor cost, forecast, and margin without losing the underlying record trail.',steps:['Toggle forecast comparison, then switch Bars to Lines.','Compare period and cumulative totals.','Click a plotted amount or choose a period below to inspect and export the source entries.'],detail:'Cost and productivity use the same 240 fictional ledger entries. The weekly and monthly groupings conserve hours, cost, and revenue.'},
 {question:'Is effort translating into output?',purpose:'Compare labor intensity across project phases, with explicit denominators.',steps:['Switch between Worker, Unit, and Hours.','Filter a phase, toggle series, and compare weekly versus monthly patterns.','Open a phase or reporting period to inspect the supporting entries.'],detail:'A rising hours-per-worker figure is not automatically poor performance. Scope, output mix, and completion counts provide the context needed to interpret it.'},
 {question:'Where should the portfolio review start?',purpose:'Bring schedule, cost, quality, staffing, and forecast signals into one review.',steps:['Select a project in the schedule × cost matrix.','Expand a response-timing row to follow detection, acknowledgement, and action.','Confirm or dismiss a suggested relationship, then filter the signal feed.'],detail:'The original risk page combines multiple signals rather than declaring a project risky from one metric. The fictional portfolio illustrates triage and traceability, not a validated prediction of failure.'}
];
export function Guide({view}:{view:number}){const g=guides[view];if(!g)return null;return <details className="workspace-guide" key={view}><summary>{g.question}<span>How to explore this view</span></summary><div className="guide-body"><div><p>{g.purpose}</p><p>{g.detail}</p></div><ol>{g.steps.map(s=><li key={s}>{s}</li>)}</ol></div></details>}
export function Overview({onSelect}:{onSelect:(n:number)=>void}){return <section className="example-body workspace-overview"><p className="overview-kicker">A project, from source records to decisions</p><h2>Explore the work behind the dashboard.</h2><p className="overview-lead">Planning tools are more useful when the schedule, people, financials, and review decisions can be traced. These working examples adapt the application components I built, using entirely fictional projects and records.</p><div className="workflow-path"><span>01 / Bring data in</span><span>02 / Review the plan</span><span>03 / Understand performance</span><span>04 / Decide & record</span></div><div className="feature-index">{[2,0,1,3,6,7,5,4,8].map(n=><button key={n} onClick={()=>onSelect(n)}><span className="feature-number">{String(n+1).padStart(2,'0')}</span><span><strong>{views[n]}</strong><span>{guides[n].purpose}</span></span><span aria-hidden="true">↗</span></button>)}</div><details className="method-note"><summary>What is real, and what is illustrative?</summary><p>The Gantt, paired heatmaps, cost/productivity/quality charts, risk page, matching engine, and parser are adapted from the supplied applications. The surrounding demo controls connect them to local examples. All project names, dates, amounts, staffing, and records are invented.</p><p>Schedule import changes the Gantt only. Cost and productivity share one ledger; capacity, forecast, quality, and portfolio risk each have their own named scenario. There are no live client connections. Edits persist while switching views and reset on reload, apart from inspection settings stored separately in the browser.</p></details></section>}
