import {useState} from 'react';
import HeatmapGrid from './components/assignments/HeatmapGrid';
import {roles,rates,downloadCsv} from './data';
const periods=Array.from({length:12},(_,i)=>new Date(Date.UTC(2026,8+i,1)).toISOString().slice(0,10));
export default function Heatmaps(){
 const [unit,setUnit]=useState('fte'),[granularity,setGranularity]=useState('month'),[role,setRole]=useState('All roles'),[extra,setExtra]=useState(0),[selected,setSelected]=useState<any>(null),[gap,setGap]=useState(false);
 const make=(mode:string)=>roles.filter(r=>role==='All roles'||r===role).map(label=>{const r=roles.indexOf(label);return {label,cells:periods.map((period,m)=>{const demand=Math.max(.2,1.8+Math.sin((m+r)*.7)*1.2+(r%2)*.6),allocation=1.5+(r%3)*.3+Number(extra);const hours=(mode==='demand'?demand:gap?allocation-demand:allocation)*160;return {period,value:unit==='fte'?hours/160:unit==='pct'?hours/(allocation*160)*100:unit==='cost'?hours*rates[r]:hours,tooltip:`${label} · ${period} · ${mode==='demand'?'Demand':'Allocation'} ${Math.round(hours)} h`}})}});
 return <div className="example-body"><h2>Role demand & capacity</h2><p>The original paired heatmaps: synchronized scrolling, demand versus allocation, capacity gaps, and cell-level review. Weekly and daily views inherit monthly values, as in the source component.</p><div className="example-controls"><label>Role<select value={role} onChange={e=>setRole(e.target.value)}>{['All roles',...roles].map(x=><option key={x}>{x}</option>)}</select></label><label>Display units<select value={unit} onChange={e=>setUnit(e.target.value)}>{['fte','hours','pct','cost'].map(x=><option key={x}>{x}</option>)}</select></label><label>Time scale<select value={granularity} onChange={e=>setGranularity(e.target.value)}>{['month','week','day'].map(x=><option key={x}>{x}</option>)}</select></label><label>Additional capacity (FTE)<input type="number" min="0" max="5" step="0.25" value={extra} onChange={e=>setExtra(Math.max(0,Math.min(5,Number(e.target.value))))}/></label><button className="btn" aria-pressed={gap} onClick={()=>setGap(!gap)}>{gap?'Show allocation':'Show capacity gap'}</button><button className="btn" onClick={()=>downloadCsv('sample-demand.csv',make('demand').flatMap(r=>r.cells.map(c=>({role:r.label,...c,unit}))))}>Export demand ↓</button></div><h3>Demand</h3><HeatmapGrid rows={make('demand')} periods={periods} mode="demand" unit={unit as any} granularity={granularity as any} syncId="demo-pair" onCellClick={(r,c)=>setSelected({role:r.label,...c,kind:'Demand'})}/><h3 style={{marginTop:24}}>{gap?'Capacity gap':'Allocation'}</h3><HeatmapGrid rows={make('allocated')} periods={periods} mode={gap?'gap':'allocated'} unit={unit as any} granularity={granularity as any} syncId="demo-pair" onCellClick={(r,c)=>setSelected({role:r.label,...c,kind:gap?'Capacity gap':'Allocation'})}/>{selected&&<div className="example-note" role="status"><strong>{selected.role} / {selected.period}</strong><p>{selected.kind}: {selected.value.toFixed(2)} {unit}. This fictional scenario uses a 160-hour month. Adjust capacity above to compare staffing choices.</p></div>}</div>
}
