import {useMemo,useState} from 'react';
import {runDeterministicMatch} from './lib/matching';
import MppPicker from './components/mapping/MppPicker';
import HoursByDestination from './components/mapping/HoursByDestination';
import {originalRows as rows,downloadCsv} from './data';
const buckets=rows.filter(r=>r.type==='task').slice(0,16).map((r,i)=>({phase:rows.find(p=>p.id===r.parent_id)!.name,task:i===3?'Unclassified support':i===9?'Equipment specifications':r.name,hours:12+i*3,cost:(12+i*3)*100}));
export default function Mapping(){const [threshold,setThreshold]=useState(.65),[overrides,setOverrides]=useState<Record<string,any>>({}),[picker,setPicker]=useState<any>(null),[applied,setApplied]=useState<any[]>([]),[filter,setFilter]=useState('All');
 const phases=rows.filter(r=>r.type==='phase'),tasks=rows.filter(r=>r.type==='task');
 const matched=useMemo(()=>runDeterministicMatch(buckets,phases,tasks.map(t=>({...t,phaseId:t.parent_id})),{taskThreshold:threshold}).map((r,i)=>({...r,...overrides[i],key:String(i)})),[threshold,overrides]);
 const hierarchy=tasks.map(t=>({id:t.id,name:t.name,table:'tasks' as const,breadcrumb:`Atlas program > ${phases.find(p=>p.id===t.parent_id)?.name} > ${t.name}`}));
 const visible=matched.filter(r=>filter==='All'||(filter==='Unmapped'?!r.mppTaskId:!!r.mppTaskId));
 const tree=phases.map(p=>({id:p.id,name:p.name,kind:'phase' as const,breadcrumb:[p.name],actual_hours:applied.filter(r=>r.mppPhaseId===p.id).reduce((s,r)=>s+r.hours,0),children:tasks.filter(t=>t.parent_id===p.id).map(t=>({id:t.id,name:t.name,kind:'task' as const,breadcrumb:[p.name,t.name],actual_hours:applied.filter(r=>r.mppTaskId===t.id).reduce((s,r)=>s+r.hours,0),source_buckets:applied.filter(r=>r.mppTaskId===t.id).map(r=>({bucket_id:r.key,phase:r.phase,task:r.task,hours:r.hours,entries:1}))}))}));
 return <div className="example-body"><h2>Timesheet → MS Project reconciliation</h2><p>The original deterministic matching engine, destination picker, and hierarchical hours drilldown. Match by phase and task, review uncertain results, and apply only the reviewed rows to a local snapshot.</p><div className="example-controls"><label>Match threshold<input type="number" step=".05" min="0" max="1" value={threshold} onChange={e=>setThreshold(Math.max(0,Math.min(1,Number(e.target.value))))}/></label><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Mapped','Unmapped'].map(x=><option key={x}>{x}</option>)}</select></label><button className="btn" onClick={()=>setApplied(matched.filter(r=>r.mppTaskId))}>Apply mapped rows locally</button><button className="btn" disabled={!applied.length} onClick={()=>downloadCsv('sample-mapping-receipt.csv',applied)}>Export receipt ↓</button><button className="btn" onClick={()=>{setOverrides({});setApplied([]);setThreshold(.65)}}>Reset</button></div><div className="example-stats"><span>Source hours<strong>{buckets.reduce((s,r)=>s+r.hours,0)}</strong></span><span>Mapped hours<strong>{matched.filter(r=>r.mppTaskId).reduce((s,r)=>s+r.hours,0)}</strong></span><span>Unmapped hours<strong>{matched.filter(r=>!r.mppTaskId).reduce((s,r)=>s+r.hours,0)}</strong></span><span>Applied hours<strong>{applied.reduce((s,r)=>s+r.hours,0)}</strong></span></div><div className="example-scroll"><table className="example-table"><thead><tr>{['Source phase / task','Hours','Destination','Match','Review'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.key}><td>{r.phase}<br/>{r.task}</td><td>{r.hours}</td><td>{r.mppTaskName||'Unmapped'}</td><td>{r.matchKind} · {(r.score*100).toFixed(0)}%</td><td><button className="btn" onClick={()=>setPicker(r)}>Choose destination</button></td></tr>)}</tbody></table></div>{picker&&<MppPicker bucketLabel={picker.task} hierarchy={hierarchy} onClose={()=>setPicker(null)} onApply={item=>{const t=tasks.find(t=>t.id===item.target_id)!;setOverrides({...overrides,[picker.key]:{mppTaskId:t.id,mppTaskName:t.name,mppPhaseId:t.parent_id,matchKind:'manual',score:1}});setPicker(null)}}/>}<h3 style={{marginTop:28}}>Applied hours by destination</h3><HoursByDestination tree={applied.length?tree:[]} onOpenBucket={id=>{const r=matched.find(r=>r.key===id);if(r)setPicker(r)}}/></div>
}
