import {useState} from 'react';
import CostChart from './components/cost/CostChart';
import ProductivityChart from './components/productivity/ProductivityChart';
import {financialRows,productivityRows,traceRows,phaseNames,ledger,type LedgerRow} from './reporting-data';
import {downloadCsv} from './data';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export default function Reporting({kind}:{kind:'cost'|'productivity'}){
 const [scale,setScale]=useState<'month'|'week'>('month'),[trace,setTrace]=useState<{period:string|null;phase?:string;label:string;cumulative?:boolean}|null>(null),[phase,setPhase]=useState('All phases');
 const scopeRows=ledger.filter(r=>kind==='cost'||phase==='All phases'||r.phase===phase);const periods=financialRows(scale).map(p=>kind==='productivity'?{...p,actual_hours:traceRows(p.period,scale,phase==='All phases'?undefined:phase).reduce((n,r)=>n+r.hours,0)}:p),phases=productivityRows(scale).filter(p=>phase==='All phases'||p.phase===phase);const records=trace?traceRows(trace.period,scale,trace.phase,trace.cumulative):[];
 function changeScale(g:'month'|'week'){setScale(g);setTrace(null)}
 const total=(key:keyof LedgerRow)=>scopeRows.reduce((n,r)=>n+Number(r[key]),0);
 return <section className="example-body reporting-workspace"><h2>{kind==='cost'?'Cost, revenue & forecast':'Productivity by phase'}</h2><p>{kind==='cost'?'Compare actual and planned spend, inspect margin, and trace a plotted amount to the time entries that produced it.':'Separate effort from output. Compare phase hours, hours per worker, and hours per delivered unit before opening the source entries.'}</p><div className="example-stats">{kind==='cost'?<><span>Actual revenue<strong>{money(total('revenue'))}</strong></span><span>Actual cost<strong>{money(total('cost'))}</strong></span><span>Margin<strong>{((1-total('cost')/total('revenue'))*100).toFixed(1)}%</strong></span></>:<><span>Recorded effort<strong>{total('hours').toLocaleString()} h</strong></span><span>Delivered units<strong>{total('units')}</strong></span><span>Source entries<strong>{scopeRows.length}</strong></span></>}</div>
 {kind==='productivity'&&<div className="example-controls"><label>Phase scope<select value={phase} onChange={e=>{setPhase(e.target.value);setTrace(null)}}>{['All phases',...phaseNames].map(p=><option key={p}>{p}</option>)}</select></label></div>}
 <div className="instrument-scroll">{kind==='cost'?<CostChart rows={periods} granularity={scale} onGranularity={changeScale} onTraceCost={(period,label,cumulative)=>setTrace({period,label:`Cost · ${label}`,cumulative})} onTraceRevenue={(period,label,cumulative)=>setTrace({period,label:`Revenue · ${label}`,cumulative})}/>:<ProductivityChart phases={phases} blMetric={scale==='week'?32:128} blUnit={8} granularity={scale} onGranularity={changeScale} onTrace={arg=>setTrace({period:arg.period||null,phase:arg.phase,label:arg.label,cumulative:arg.cumulative})}/>}</div>
 <details className="method-note"><summary>How to read this chart</summary>{kind==='cost'?<p>Revenue is hours × the sample billing rate; cost is hours × the sample labor rate. Margin is (revenue − cost) ÷ revenue. The dashed forecast assumes 32 hours per specialist per week. Cumulative mode adds preceding periods; opening a cumulative amount includes those entries in the trace.</p>:<p>Worker mode divides period hours by distinct workers in each phase. Unit mode uses cumulative hours divided by the scenario’s final delivered-unit count, following the source component. It is an effort-per-output comparison, not a live completion forecast. Week/month grouping preserves total hours. The reference lines are illustrative planning assumptions.</p>}<p>This reporting scenario uses 240 invented entries across four phases and twelve fictional specialists. It is separate from an uploaded MS Project schedule.</p></details>
 <div className="example-controls"><h3>Open the source records</h3><button className="btn" onClick={()=>setTrace({period:null,phase:phase==='All phases'?undefined:phase,label:'All reporting entries'})}>Review all entries</button><button className="btn" onClick={()=>downloadCsv(`sample-${kind}-summary.csv`,kind==='cost'?periods:phases.map(({weekly,...rest})=>rest))}>Export summary ↓</button></div>
 <div className="period-index" aria-label="Trace a reporting period">{periods.map(p=><button className="btn" key={p.period} onClick={()=>setTrace({period:p.period,phase:phase==='All phases'?undefined:phase,label:p.period})}>{p.period.slice(0,scale==='month'?7:10)} <span>{p.actual_hours.toLocaleString()} h</span></button>)}</div>
 {trace&&<section className="trace-panel" aria-label="Source record trace"><div className="example-controls"><h3>{trace.label}</h3><button className="btn" onClick={()=>downloadCsv(`sample-${kind}-trace.csv`,records)}>Export these {records.length} entries ↓</button><button className="btn" onClick={()=>setTrace(null)}>Close trace</button></div><p role="status">{records.length} source entries · {records.reduce((n,r)=>n+r.hours,0).toLocaleString()} hours · {money(records.reduce((n,r)=>n+r.cost,0))} cost · {money(records.reduce((n,r)=>n+r.revenue,0))} revenue</p><div className="example-scroll"><table className="example-table"><thead><tr>{['Week','Phase','Specialist','Work package','Hours','Cost','Revenue','Units'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.week}</td><td>{r.phase}</td><td>{r.worker}</td><td>{r.work_package}</td><td>{r.hours}</td><td>{money(r.cost)}</td><td>{money(r.revenue)}</td><td>{r.units}</td></tr>)}</tbody></table></div></section>}
 </section>
}
