// Entirely invented portfolio; aggregates are derived from the same signal rows.
const snapshot='2026-09-28';
const specs=[['schedule','slip','Schedule exceeds baseline','days'],['cost','overrun','Forecast exceeds approved cost','USD'],['quality','open_defects','Verification items remain open','items'],['resourcing','allocation_gap','Planned demand exceeds allocation','hours'],['forecast','pending_sprint_delta','Effort revision awaiting review','hours'],['cost','thin_margin','Commercial margin below planning threshold','percent']] as const;
const names=['Atlas delivery','Cedar process upgrade','Harbor controls','Orion data platform','Summit utilities','Willow assurance'];
const target:Record<string,number>={schedule:0,cost:6,quality:5,resourcing:1,forecast:4,productivity:7};
export const riskSignals=names.flatMap((name,p)=>specs.filter((_,i)=>p===0||((i+p)%3!==0)).map(([source,kind,title,unit],i)=>({id:`signal-${p}-${i}`,source,kind,severity:(p+i)%4===0?'p1':(p+i)%3===0?'p3':'p2',project_id:`portfolio-${p}`,project_name:name,customer_name:null,title:`${title}: ${name}`,detail:source==='schedule'?`${7+p*3} days of schedule exposure. Review sequencing and the next approval gate.`:source==='cost'?`Review remaining effort and role rates against the approved baseline. Example amount: $${(8000+p*6500).toLocaleString()}.`:'Review the related source records and assign a next action.',metric_value:unit==='USD'?8000+p*6500:unit==='days'?7+p*3:unit==='percent'?8+p:12+p*4,metric_unit:unit,drill_href:`#view-${target[source]}`,observed_on:snapshot,first_seen:`2026-09-${String(12+p+i).padStart(2,'0')}`,age_days:16-p-i})));
const projects=names.map((name,p)=>{const rows=riskSignals.filter(s=>s.project_id===`portfolio-${p}`);return {project_id:`portfolio-${p}`,project_name:name,customer_name:null,n:rows.length,p1:rows.filter(s=>s.severity==='p1').length,p2:rows.filter(s=>s.severity==='p2').length,sources:[...new Set(rows.map(s=>s.source))],exposure:rows.filter(s=>s.metric_unit==='USD').reduce((n,s)=>n+s.metric_value,0),max_age_days:Math.max(...rows.map(s=>s.age_days))}});
const sources=[...new Set(riskSignals.map(s=>s.source))];
export const initialCorrelations=projects.slice(0,3).map((p,i)=>({raid_id:`review-${i}`,raid_type:'risk',raid_title:['Design approval dependency','Estimate-to-complete review','Verification backlog'][i],raid_severity:'high',project_id:p.project_id,project_name:p.project_name,links:riskSignals.filter(s=>s.project_id===p.project_id).slice(0,2).map(s=>({...s,signal_id:s.id,match_kind:'suggested',confidence:.75}))}));
let correlations=structuredClone(initialCorrelations);
export function resetRisk(){correlations=structuredClone(initialCorrelations)}
export function riskPayload(){const count=(sev:string)=>riskSignals.filter(s=>s.severity===sev).length;const ages=riskSignals.map(s=>s.age_days).sort((a,b)=>a-b);return {success:true,observed_on:snapshot,kpis:{total:riskSignals.length,p1:count('p1'),p2:count('p2'),p3:count('p3'),projects_affected:projects.length,posture:'at_risk',posture_banner:'Review schedule and cost exposure together.',median_age_days:ages[Math.floor(ages.length/2)],p75_age_days:ages[Math.floor(ages.length*.75)],p95_age_days:ages[Math.floor(ages.length*.95)]},lifecycle:{new_today:0,cleared_yesterday:0},trend:Array.from({length:30},(_,i)=>{const day=new Date(Date.UTC(2026,7,30+i)).toISOString().slice(0,10);const active=riskSignals.filter(s=>s.first_seen<=day);const n=(sev:string)=>active.filter(s=>s.severity===sev).length;return {day,p1:n('p1'),p2:n('p2'),p3:n('p3'),info:0,total:active.length}}),by_source:sources.map(source=>({source,n:riskSignals.filter(s=>s.source===source).length,p1:riskSignals.filter(s=>s.source===source&&s.severity==='p1').length})),top_projects:projects.map(p=>({...p,score:p.p1*4+p.p2*2+(p.n-p.p1-p.p2)+p.max_age_days/7})).sort((a,b)=>b.score-a.score),projects,signals:riskSignals,raid_correlations:correlations,clusters:projects.filter(p=>p.sources.length>=3).map(p=>({...p,source_count:p.sources.length})),co_occurrence:sources.flatMap((a,i)=>sources.slice(i+1).map(b=>({source_a:a,source_b:b,projects:projects.filter(p=>p.sources.includes(a)&&p.sources.includes(b)).length}))),kind_groups:specs.map(([source,kind,title])=>{const signals=riskSignals.filter(s=>s.source===source&&s.kind===kind);return {source,kind,n_signals:signals.length,n_projects:signals.length,n_p1:signals.filter(s=>s.severity==='p1').length,exposure:signals.filter(s=>s.metric_unit==='USD').reduce((n,s)=>n+s.metric_value,0),sample_title:title,top_projects:signals.map(s=>({project_id:s.project_id,project_name:s.project_name}))}})}}
export function timingPayload(){const incidents=riskSignals.filter(s=>s.kind==='slip'||s.kind==='overrun').map((s,i)=>({...s,detected_on:s.first_seen,latest_on:snapshot,latest_severity:s.severity,count_latest:1,metric_at_detection:s.metric_value+(i%3===0?5:-3),metric_latest:s.metric_value,first_ack_at:i%4===0&&i%3!==0?null:s.first_seen+'T12:00:00Z',first_ack_kind:i%4===0&&i%3!==0?null:'raid_comment',days_to_ack:i%4===0&&i%3!==0?null:.5,first_action_at:i%3===0?s.first_seen+'T18:00:00Z':null,first_action_kind:i%3===0?'mitigation_set':null,days_to_action:i%3===0?.75:null,trend_after:i%3===0?'improved':i%4===0?'worsened':'stable',open_raid_count:2}));const ack=incidents.filter(i=>i.first_ack_at),acted=incidents.filter(i=>i.first_action_at);return {success:true,incidents,kpis:{n_detections:incidents.length,n_acknowledged:ack.length,n_actioned:acted.length,pct_acknowledged:ack.length/incidents.length,pct_actioned:acted.length/incidents.length,pct_improved_after_action:1,avg_days_to_ack:.5,median_days_to_ack:.5,avg_days_to_action:.75,median_days_to_action:.75}}}
export async function riskFetch(url:string,options?:RequestInit){let result:any;if(url.startsWith('/api/risk/correlations')&&options?.method==='POST'){const action=JSON.parse(String(options.body));for(const c of correlations)if(c.raid_id===action.raid_item_id){if(action.action==='dismiss')c.links=c.links.filter(l=>l.signal_id!==action.signal_id);else c.links=c.links.map(l=>l.signal_id===action.signal_id?{...l,match_kind:'manual',confidence:1}:l)}result={success:true}}else result=url.includes('/timing')?timingPayload():riskPayload();return new Response(JSON.stringify(result),{headers:{'Content-Type':'application/json'}})}
